apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-demo
  labels:
    app: blue-green-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green-demo
  template:
    metadata:
      labels:
        app: blue-green-demo
    spec:
      containers:
        - name: blue-green-demo
          image: kanhaiya05/blue-green-demo:latest
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "argocd-v1"